import os
from os import path

from dotenv import dotenv_values

CURRENT_WORKING_DIR = os.getcwd()

PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
CHROMA_COLLECTION_NAME = os.getenv("CHROMA_COLLECTION_NAME")
CHROMA_PERSIST_DIRECTORY = os.path.join(
    CURRENT_WORKING_DIR, os.getenv("CHROMA_PERSIST_DIRECTORY")
)
OPENAI_EMBEDDING_MODEL = os.getenv("OPENAI_EMBEDDING_MODEL")
OPENAI_MODEL = os.getenv("OPENAI_MODEL")
GEMINI_MODEL = os.getenv("GEMINI_MODEL")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
MONGO_URI = os.getenv("MONGO_URI")
DATABASE_NAME = os.getenv("DATABASE_NAME")
HOST = os.getenv("HOST")
PORT = int(os.getenv("PORT"))
ENVIRONMENT = os.getenv("ENVIRONMENT")
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

GOOGLE_EMBEDDING_MODEL =os.getenv("GOOGLE_EMBEDDING_MODEL")